Add a hint about the bash scripts to the documentation
MeteoSwiss-APN/mch-python-blueprint pull request #114
Opened 2023-04-05 16:32 UTC by clairemerker

Users tried to use the `tools/setup_miniconda.sh` script in sourcing it instead of executing it. This breaks the argument parsing of the script. It relies on `OPTIND` which is not reset when calling the script again, and the script then ignores the arguments. 
I included a hint in the documentation at two locations.

2023-04-05 16:46 UTC, clairemerker commented
launch jenkins

2023-04-21 13:56 UTC, twicki approved these changes
LGTM

2023-04-21 13:58 UTC, twicki commented
we could add this barrier https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced to the script to prevent the users - in order to make it safer

2023-08-22 10:06 UTC, twicki requested changes

2023-08-22 10:06 UTC, twicki commented on .github/workflows/blueprint-docs.yml
> +        conda run --name blueprint copier copy --force --vcs-ref=HEAD . ./docs/example_project
why is the python version removed here? 

If we really want to / need to remove it, adopt the comment above

2023-10-23 13:23 UTC, twicki commented
closed in favor of https://github.com/MeteoSwiss-APN/mch-python-blueprint/pull/121

2023-10-23 13:23 UTC, closed without merging