Merge `tox.ini` and `setup.py` into `pyproject.toml`
MeteoSwiss-APN/mch-python-blueprint pull request #48
Opened 2022-09-21 13:38 UTC by ruestefa

2022-09-22 18:13 UTC, ruestefa commented
Add `run-mypy.sh` script to run `mypy` and use it in `pre-commit` and github actions. Motivation: `mypy` should always be applied to the whole code base, not just over the changed files, changes can introduce bugs in other files. (In addition, running `mypy` locally (i.e., in the active dev env, not in an isolated pre-commit env) makes all deps available to mypy, which otherwise would all have to be installed in the pre-commit env.)

2022-10-06 11:17 UTC, regDaniel requested changes
Again, quick discussion on code overhead, in terms of technical content I agree.

2022-10-13 08:32 UTC, ruestefa commented on {{cookiecutter.project_slug}}/test_all.sh
> +#!/bin/bash
Removed.

2022-10-13 08:32 UTC, ruestefa commented on {{cookiecutter.project_slug}}/requirements/dev-requirements.yml
> +  # - tox
Deleted.

2022-10-13 08:47 UTC, ruestefa commented
Merged #47 here and closed that PR.

2022-10-13 08:57 UTC, regDaniel approved these changes

2022-10-13 09:00 UTC, regDaniel commented
I think we can merge what is in this PR.

2022-11-06 11:52 UTC, cosunae commented
launch jenkins

2022-11-06 12:10 UTC, cosunae commented
launch jenkins

2022-11-06 12:22 UTC, cosunae commented
I fixed jenkins for the blueprint. The one of the project (template) is still broken, not adapted to latest changes of the install. But since it is not tested here, I will create an issue to fix that later. 
I will merge

2022-11-06 12:23 UTC, merged