Fix and extend github actions workflows
MeteoSwiss-APN/mch-python-blueprint pull request #50
Opened 2022-09-22 10:26 UTC by ruestefa

The actions workflow `precommit` so far tested `pre-commit run -a` on the blueprint project itself, but used the requirements files of the template to create the dev env, which broke after I added `python>={{cookiecutter.python_version}}` to `{{cookiecutter.project_slug}}/requirements/requirements.txt` because the jinja template was of course still there.

Tasks:
- [ ] Add requirements and environment files to the blueprint itself (with `cookiecutter` as the sole run req and `pre-commit` the sole dev req)
- [ ] Adapt `.github/workflows/precommit.yml` to use those requirements files, and clean it up
- [ ] Add new workflow that creates a project from the template and runs pre-commit (and possibly pytest etc.) on that

2022-09-22 15:43 UTC, ruestefa commented
Adapted existing workflows a bit more (names etc.)

New workflow now does the following:
- Create new project (incl. git init etc.)
- Create dev env and install project in there
- Run pre-commit hooks (incl. black, isort, pydocstyle, flake8)
- Run the major hooks again directly to ensure they validate also on their own
- Run mypy (not in pre-commit, but should be)
- Run pylint (not in pre-commit; should it be?)
- Run pytest

2022-10-06 07:00 UTC, regDaniel requested changes
We should briefly discuss about having a package build in pre-commit and wheter this is worth having another pre-commit file in the repo as we already do this through Jenkins. But maybe I am missing something here.

2022-10-06 07:00 UTC, regDaniel commented on .github/workflows/new-project.yml
> +        conda run --name flying-circus-dev pytest
If I understand correctly, this triggers the creation and testing of a new "dummy" project through pre-commit. We already do this in Jenkins upon merges to the main branch. I think we should decide if we do it with Jenkins or pre-commit, but doing it twice seems to be a bit much to me.

2022-10-06 07:00 UTC, regDaniel commented on .github/workflows/blueprint-pre-commit.yml
> +name: Run pre-commit in blueprint
this is mainly a renaming to make things clearer right? Seems reasonable to me.

2022-10-06 09:39 UTC, regDaniel commented on .github/workflows/new-project.yml
> +        conda run --name flying-circus-dev pytest
ah yes sorry. Anyways Jenkins is a mandatory reviewer for pushes to the main. But if it works reasonably well, we could even think about dropping the corresponding action in Jenkins. However I didn't really think this through yet and I'd also be curious on what @cosunae thinks.

2022-10-13 08:24 UTC, ruestefa commented
Closing as changes and adaptations are already in #47 .

2022-10-13 08:24 UTC, closed without merging