Merge dev-requirements into requirements
MeteoSwiss-APN/mch-python-blueprint pull request #87
Opened 2023-01-05 15:26 UTC by ruestefa

See #86

2023-01-09 18:13 UTC, ruestefa commented
See https://github.com/MeteoSwiss-APN/mch-python-blueprint/issues/86#issuecomment-1376047824

2023-01-12 16:53 UTC, ruestefa commented
launch jenkins

2023-01-12 17:59 UTC, ruestefa commented
launch jenkins

2023-01-12 18:00 UTC, ruestefa commented
Already contains #92

2023-01-13 12:44 UTC, regDaniel commented
> Already contains #92

Perfect, I approved #92 and will proceed with the review of this one.

2023-01-13 13:00 UTC, regDaniel requested changes
We should rephrase the few sentences on the installation process in `tmpl/docs/installation.rst.j2`. Otherwise it looks fine to me.

2023-01-14 12:29 UTC, ruestefa commented on .pre-commit-config.yaml
> +        -   tomli
Indeed, I've been annoyed by this, as well. I probably would've gone for the shorter `.yml`, but if the official recommendation is `.yaml`, then `.yaml` it shall be.

2023-01-14 12:31 UTC, ruestefa commented on tmpl/docs/installation.rst.j2
> +Dependencies are handled by the conda package manager. The goal of this step is to set up a conda environment according to the requirements of {{ project_name }}. Note that the development installati
Yeah, I didn't revise the instructions in full, I just searched for the file names and fixed the respective sentences...

2023-01-17 15:57 UTC, regDaniel commented
launch jenkins

2023-01-17 16:46 UTC, ruestefa commented
launch jenkins

2023-01-17 17:00 UTC, regDaniel approved these changes

2023-01-17 17:25 UTC, regDaniel commented
launch jenkins

2023-01-18 10:31 UTC, regDaniel commented
launch jenkins

2023-01-18 10:44 UTC, merged